# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  salesforce-apex: circleci/salesforce-apex@1.0.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  push-metadata:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - apex/setup:
          defaultusername: himanshu@bluepineapple.com
      - apex/mdapi-deploy:
          checkonly: false
          deploy-dir: /force-app/main/default
          scratch-alias: scratchorg
          wait-time: -1

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  push-metadata-workflow:
    jobs:
      - push-metadata
